build:
	g++ -std=gnu++0x -g -no-pie preferencias_DyV.cpp -o preferencias_DyV
	g++ -std=gnu++0x -g -no-pie preferencias_secuencial.cpp -o preferencias_secuencial

clean:
	rm -rf preferencias_DyV preferencias_secuencial
